- name: composer
  src: geerlingguy.composer
  version: 1.7.6

- name: ntp
  src: geerlingguy.ntp
  version: 1.6.4

- name: logrotate
  src: nickhammond.logrotate
  version: v0.0.5

- name: swapfile
  src: oefenweb.swapfile
  version: v2.0.22

- name: mailhog
  src: geerlingguy.mailhog
  version: 2.1.4

- name: princexml
  src: pressbooks.princexml
  version: 12.5.0

- name: kindlegen
  src: softasap.sa-publishing-kindlegen
  version: 1.1.0

- src: geerlingguy.redis
  version: 1.6.0
